export const rooms = [
  {
    slug: "apartament-1",
    name: "Apartament 1",
    size: 20,
    maxGuests: 5,
    beds: "King size + pojedyncze + sofa rozkładana 150cm",
    features: ["balkon", "klimatyzacja", "biurko", "wanna narożna"],
    view: "Łąki nadwarciańskie, strona południowo-zachodnia",
    bathroom: "Wanna narożna, umywalka z szafką, lustro podświetlane, suszarka",
    description:
      "Przestronny apartament z balkonem i widokiem na łąki nadwarciańskie. Klimatyzacja, łóżko King size, biurko do pracy.",
    image: "/images/rooms/apartament-1.jpg",
  },
  {
    slug: "apartament-2",
    name: "Apartament 2",
    size: 20,
    maxGuests: 5,
    beds: "King size + pojedyncze + sofa rozkładana 150cm",
    features: ["balkon", "klimatyzacja", "biurko", "wanna narożna"],
    view: "Łąki nadwarciańskie, strona południowo-zachodnia",
    bathroom: "Wanna narożna, umywalka z szafką, lustro podświetlane, suszarka",
    description: "Lustrzane odbicie Apartamentu 1 — ten sam komfort, widok i wyposażenie.",
    image: "/images/rooms/apartament-1.jpg",
  },
  {
    slug: "pokoj-3",
    name: "Pokój 3",
    size: 15,
    maxGuests: 4,
    beds: "2 łóżka pojedyncze 90cm + sofa rozkładana",
    features: ["Netflix", "biurko", "stoliczek kawowy"],
    view: "Zachód — łąki i las po drugiej stronie",
    bathroom: "Prysznic, lustro podświetlone, ogrzewanie podłogowe",
    description:
      "Kompaktowy pokój z widokiem na zachód. Dwa łóżka z możliwością łączenia, sofa dla dodatkowych gości.",
    image: "/images/otoczenie/otoczenie-2.jpg",
  },
  {
    slug: "apartament-4",
    name: "Apartament 4",
    size: 25,
    maxGuests: 6,
    beds: "King size + 2 pojedyncze 90cm + sofa rozkładana 160cm",
    features: ["Netflix", "biurko", "szafa na ubrania"],
    view: "Zachód — łąka i las",
    bathroom: "Duża łazienka z prysznicem, szafka z dwoma półkami, lustro podświetlane",
    description:
      "Największy apartament w dworku — 25 m² z czterema miejscami do spania. Idealny dla rodzin.",
    image: "/images/otoczenie/otoczenie-3.jpg",
  },
  {
    slug: "apartament-5",
    name: "Apartament 5",
    size: 22,
    maxGuests: 6,
    beds: "King size + sofa rozkładana 160cm",
    features: ["balkon", "widok na wolierę z papugami"],
    view: "Wschód — nad wejściem głównym, widok na łąki, pola, las, woliera z ptakami",
    bathroom: "Duża łazienka retro, duży prysznic z szybą, otwarty brodzik",
    description:
      "Apartament z balkonem nad wejściem głównym. Z balkonu widać wolierę z papugami i gołębiami w ogrodzie.",
    image: "/images/rooms/apartament-5.jpg",
  },
  {
    slug: "apartament-debowy-6",
    name: "Apartament Dębowy",
    size: 15,
    maxGuests: 4,
    beds: "King size + sofa rozkładana 160cm",
    features: ["lamele dębowe", "obraz dębu na ścianie", "wykładzina aksamitna"],
    view: "Ogrody, starodrzew akacji, skarpa nad starorzeczem Warty",
    bathroom: "Wanna narożna, przytulna łazienka",
    description:
      "Przytulny apartament z lamelami z naturalnego drewna dębowego i widokiem na starodrzew akacji na skarpie nad starorzeczem.",
    image: "/images/rooms/apartament-debowy.jpg",
  },
  {
    slug: "apartament-trzcinowy-7",
    name: "Apartament Trzcinowy",
    size: 15,
    maxGuests: 2,
    beds: "2 łóżka pojedyncze 100cm z możliwością łączenia",
    features: ["klimatyzacja", "LED podświetlenie ściany", "obraz trzcin i szuwarów"],
    view: "Ogrody i starodrzew akacji",
    bathroom: "Prysznic, czarne baterie, szafka drewnopodobna",
    description:
      "Jasny, dwuosobowy apartament z klimatyzacją. Ściana z łóżkami podświetlona LED-em w ciepłym kolorze.",
    image: "/images/otoczenie/otoczenie-4.jpg",
  },
  {
    slug: "apartament-nad-rzeka-8",
    name: "Apartament Nad Rzeką",
    size: 18,
    maxGuests: 4,
    beds: "King size + możliwość dostawki",
    features: ["balkon", "klimatyzacja", "biurko", "obraz rzeki i mostka"],
    view: "Tylna strona dworku — stara stajnia, parking",
    bathroom: "Bardzo duża i przestronna, prysznic, szafa, szafka drewniana",
    description:
      "Słoneczny apartament z balkonem i klimatyzacją. Obraz rzeki, mostka na Wartą i okolicznych dębów na ścianie.",
    image: "/images/otoczenie/otoczenie-5.jpg",
  },
] as const;

export type Room = (typeof rooms)[number];
